### ISSUE TITLE
Annex is labelled as normative even when the setting is removed

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-templates-iso#9]
Please, refer to the sample:
[annex-issue.zip](https://github.com/metanorma/mn-templates-iso/files/3791917/annex-issue.zip)

**Comment by opoudjis** [comment]
There has to be a default value of obligation (which is binary between normative and informative), otherwise the document is underspecified. We have set the default to normative. This is documented in metanorma.com:

> for annexes and clauses,
the default value of the obligation is "normative" and users need to set the obligation
to "informative" as a section attribute if needed.

ISO/IEC DIR 2 does not set a default value for obligation, and indeed it cannot: https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor274

**Comment by opoudjis** [comment]
@manuel489 Won't fix, but you should document this default in the ISO template: "If no obligation value is set, the annex is presumed to be normative."
